openapi: 3.0.0
info:
  title: HTTP API for pdjr-signalk-metadata
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    [pdjr-skplugin-metadata](https://github.com/pdjr-signalk/pdjr-skplugin-metadata)
    is a plugin for the
    [Signal K node server](https://github.com/SignalK/signalk-server).

    A Signal K server hosting the plugin will present this API under
    the root https://*server_ip*:*server_port*/plugins/metadata.
  
    Metadata resources returned by the following requests are filtered
    to exclude keys selected by the 'excludePaths' configuration
    property.
externalDocs:
  description: Plugin README document
  url: https://github.com/pdjr-signalk/pdjr-skplugin-metadata#readme 
paths:
  /metadata:
    get:
      description: |
        Get metadata resources available in the plugin's configured
        ```resourceType```.
      responses:
        200:
          description: |
            Success.
            The response body is an object consisting of metadata
            objects indexed by path.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/key-list"
        500:
          description: |
            Error.
            The server was unable to service the request.
    put:
      description: |
        Save a collection of metadata resources to the plugin's
        configured ```resource type```.
      requestBody:
        description: |
          Identifier of an existing or new resource.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/key"
      responses:
        201:
          description: |
            Success.
            The specified resource has been updated or created.
        404:
          description: |
            Error.
            The request was invalid (bad or missing reource key/value).
        405:
          description: |
            Error.
            The request was rejected because the resource repository was busy.
        500:
          description: |
            Error.
            The server was unable to service the request.
  /metadata/{key}:
    get:
      description: |
        Get the value of a specified metadata resource in the plugin's
        configured ```resource type```.
      parameters:
      - name: key
        in: path
        description: |
          Identifier of the resource whose value is required in Signal
          K dotted path format.
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        200:
          description: |
            Success.
            The response body is the metadata object referenced by {key}.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/metadata-value"
        404:
          description: |
            Error.
            The requested {key} does not exist.
        500:
          description: |
            Error.
            The server was unable to service the request.
    put:
      description: |
        Update or create a metadata resource for the specified {key}.
        The supplied metadata will be saved to the resource provider
        and injected into the Signal K tree.
      parameters:
      - name: key
        in: path
        description: |
          Identifier of the resource to be created/updated.
        required: true
        schema:
          type: string
      requestBody:
        description: |
          New or replacement metadata object.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/metadata-value"
      responses:
        201:
          description: |
            Success.
            The specified resource has been updated or created.
        404:
          description: |
            Error.
            The request was invalid (bad or missing reource key/value).
        405:
          description: |
            Error.
            The request was rejected because the resource repository was busy.
        500:
          description: |
            Error.
            The server was unable to service the request.
    delete:
      description: |
        Delete the resource for a specified key.
      parameters:
      - name: key
        in: path
        description: |
          Identifier of the resource to be deleted.
        required: true
        schema:
          $ref: "#/components/schemas/key"
      responses:
        200:
          description: |
            Success.
            The specified resource has been deleted.
        404:
          description: |
            Error.
            The request was invalid (bad or missing key).
        405:
          description: |
            Error.
            The request was rejected because the resource repository was busy.
        500:
          description: |
            Error.
            The server was unable to service the request.
  /inject:
    patch:
      description: |
        Install all metadata resources into the Signal K tree.
      responses:
        200:
          description: |
            Success.
            All metadata values were successfully merged into the
            Signal K tree.
        405:
          description: |
            Error.
            The request was rejected because the resource repository was busy.
        500:
          description: |
            Error.
            Some, but not all, metadata files were merged into the
            Signal K tree.
  /compose:
    patch:
      description: |
        Trigger composition of metadata resources from metadata
        configuration resources.
      responses:
        200:
          description: |
            Success.
            All configuration fies were processed and new metadata
            resources merged into the resource collection.
        405:
          description: |
            Error.
            The request was rejected because the resource repository was busy.
        500:
          description: |
            Error.
            Some, but not all, configuration files were processed and
            new metadata resources may have been merged into the
            resource collection.
  /snapshot:
    patch:
      description: |
        Copy/merge all live Signal K metadata objects into the resource
        repository.
      responses:
        200:
          description: |
            Success.
            All Signal K paths were processed and metadata values
            merged into the resource collection.
        405:
          description: |
            Error.
            The request was rejected because the resource repository was busy.
        500:
          description: |
            Error.
            Some, but not all, Signal K paths may have been processed
            and metadata values merged into the resource collection.
components:
  schemas:
    key:
      description: Signal K key/path expressesed using dotted notation or the name of a metadata resource which is usually, but not necessarily, the same thing.
      example: "tanks.wasteWater.0.currentLevel"
      type: string
    key-list:
      description: Array containing a sorted list of Signal K or metadata keys.
      example: [ "tanks.wasteWater.0.currentLevel" ]
      type: array
      items:
        $ref: "#/components/schemas/key"
    metadata-value:
      type: object
      description: Single metadata value (see Signal K specification).
